### ISSUE TITLE
Unable to create agent from suggested method in README

### ISSUE THREAD

**Issue by alex-dixon** [dialogflow/fulfillment-regex-nodejs#1]
![image](https://user-images.githubusercontent.com/9045165/44594435-0b778b80-a77b-11e8-8dc0-64d4a6cc6664.png)

Selecting "Start over" will say template already exists. Viewing template in dialogflow shows an empty template. Creating template again with different name produces same error as encountered initially.

https://storage.googleapis.com/dialogflow-oneclick/Regex-matching-agent.zip

**Comment by findzaatar** [comment]
@alex-dixon 

Thanks for letting us know! Here's the correct one-click agent creation link the meantime while we update the README, https://console.dialogflow.com/api-client/oneclick?templateUrl=https://storage.googleapis.com/dialogflow-oneclick/Regex-sample.zip
